GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "test",
  "author": "Ahmed Catak",
  "url": "www.ahmedcatak.com",
  "likes": "200"
}
